name: Pathoplexus
customWebsiteImage: ghcr.io/pathoplexus/website:commit-03b2835
externalDatabase:
  urlSealedSecret: "AgAeKfipg6YiOqwteFFUhsGonPBzPlb14kMlPxl4HYeRygiwJvESJIZAcAS2/ur599Ua0p4J1NNISR4u04X3V+JC+fWsH3cMKAKnvyf03m5ct0wN7E3GnaLDMeFTlTbDqqJo/NXOdj088BXvG6KRVhpW462v2qxAuPcfZI/4Clwgvr371MqHyirtsrNQ8QUehYs3aLzfXDXU+lguYTyEbRb1eEIzVVxcxia8aejWn1b3Ujy7g1dFjQIi7p34Vgrs2b3zlxPbzF6KzarpXDWjE+XyVjcuQjXEPc/VlqfkmvgRoj28hMxosnkN4L9M8t0NUM18UZWQHaKyCSlxTAgIQAnMRuNBr9wtK8yJgTvy6uuBKZf1sVysYmkQ3R9VE4lW/ch4A5/bYNI1c15IVllVbgLO46DCXWZCEMfT+3g6LHbT6kK4PjKvHPhL+PNBYujGpMwjZ5PKvG4TwTMy5Gr0im5FDhkBjr2KxgW9XkdHR5asMEoQ+kCcyAEarEtJhqvu2vHhUHlMhyeaWoSEg0YcMmJLTcrPYWk/zvCjjrM3EYxX0dzg/fyFyjrGooNa6SvBa02xWytCroP4lJpdknPt1C9IGRt7QKyDyxr7/I/RyjEsFcqjdDxJ6PM6I3g2TTe9reZmchfi51cbNFpJfR0X7+JmmARbbdUxcO6MNigi7HXW77Fg9wJ0QU4XzwYq6mGvCOrIXqdcwUsoU3chLw59qjFsrVlrgFPBEv5c+QB2SLBFo7TZdlmj229T8u85r/oMA2yrhHaO6JfKZCSeyUQsqATRVZ9UzynrM3JFi8H3O/bwSOEvAFQNyqTTTE3+Ayjty+0KZg==" # Sealed secret for external database URL, leave empty to use the internal database
  usernameSealedSecret: "AgCc4Q+FZ7t6P5QswSBmlJYebTgFqKaoLRf6tAYp5r4fln2IcPhD0JrWIQ4YQgz/N/FpOnYdttAOHS1hjJ60pBB2907uUn8EF36VAkxNtanr1MmNhHwiOSlF6bwhlAnNCuND05q37SGA798cOnt8FPk5KCIwOdRpk196foz1SeM7DYpiY2oj12ObtyAclfM78RUc4aNxBVaRa/rGQYchZajv1DtHj45dVtI8wTLIHDYow9dedVWto53SPOY6jHTC781Am6aA+fgxabiHodDUw+COHUKxTP0JFsdO7trV8y+RwqpeS1Pjwm6yoyYTDMiAc4hGAtbIIymdIceOb3WGuJ+5bxBvcouJJ/NENkcghmEuDtp8YNiS4B2xpmaEls5ByLN1xlYaJHQbgS5CfSwJZPfjc5e2Mzjj3hBb80H2KSSwFreZjm0eh7gsTUpCE6Eg7R8fsj/dYb+gfIpYHQBlj+Bj8qIqrE5cGaegNOtaNIcc1B1IgWPx5EUTV4t064RpLNM3Ppc0EqA9Kn0RRYxq0iqHBQLbYG2GbR5snWyr5hSprN9DPT5c+25Y6zn6cYbnFFgOyaP25FzDgHTK5hCVpiOWa/2yzUPJwZIchUCg9+DbfEcPoU+zudFjXO/459Bf4e+HvP7NWgvuvCCHAEKnKdv4rZ+JgXe7xZQKHwJtxSIWXtnh91GcCnNl/I9IAWo6B8p+WaeUnPxdTeXkKTAeScPK" # Sealed secret for external database username
  passwordSealedSecret: "AgBZl7qj3dIjDwXcdr1BLRvHhI4FXbQyuz/vV20JxzbjonVzCqEAk9ll/TiFFCtDtsDpDokY5S+9ti5HHYslZ+e01wCmjEolUK4qUv/YM5PRcCm6plzSavv+FMaLSAxS/uwzdEn98xFEK3No66Ztm9yJ8WJBLarY1qgIvVm3eEzyd67OcIZitHS8F58Y1dJA++HDoGcepNqG6fL3A53axh9x0y2HYr/dt6JARIgNFOekh9NQkC6Udf0cBjz7QW9gjlw5jglKUc9W1volOgDTYnQ4pXFON1FCnGW7xKXmOlOBda100OaLtN8wnfpj+Ws4PgDGq29hFMgnFTdgq+zAN6ifRqEJz4VqNbkuv1oyzbSWq2mXp71lyADovIlxW3w0uOO0v2KiZ3Xhpc4JmqZ0zXSIQYgINmqqieDV0mD6QPvdoVKl9iF/WNsnMO1j1Cl8XbEO3jqSlhQ20K3W1Fp1HSZ5TofnHZ+iliDDkmojk6I6Muwi+m+CvApgNHVsDhiqwK0ANs4vf3DlLIz/y5TECJOFddn/ZZYYyh2B8dwu7fL3GQJoAf2jmswl4/HkDcz3Ue3ofa2KeGKCYrFTdwH3CCUqAxupYpXcV0M54wInYCcmOc2xc0cgGUVtcbrp5hs1Ue7BnLF1f2lUg8w1MV3KwKsRZUN5cU/jqlNW6N5ff73NQqQjA+42BJt/8UROiPjs8rdsjkAxfN8HucDO7VTti8eaQMSBkxqPTc8=" # Sealed secret for external database password
keycloakDatabase:
  addrSealedSecret: "AgCNOLM44zrMjvAVkYaGlS+T5L9CoxocVYOxYso/smqNjHKmvoeJVfW9oy15V7BHrBRQRAsgJooOgOi6JORdwjIBn8/xBje73PaFWLEL9nJFAwr8XnYRZeRDuRjD6Z0kVMYKia2oRYCfsLuvWOs6oVaMDCvlTdSWBK+AUO7kxzAMCA4uRZxgVRrMaJjAcRC3gO8c3KTEmnSUxnC5msRE8xSJRgVafhWxdkKfHoJcMfvfG40kQu13BNW0ZT8mDb6Xi+qOP3xpiJkMoZ7uOhVgvWk3N2ztnfAzbA9AMYJNYPVgrF/Oa3e1xfDYFCMqmHos1PC3qe/c/P56WHte6P8/3L7zJFzJud7/jGRQxoLg5P1U1c/CglQFu+UJFDfO/HxMCWZOsKOPRyamnrpgEI9KM5Acxzzy16WOvoq8YhA0f7qIGpfP5hlarFuGaDD+eVb+i5LyLNV2zXHXUxrVGFNzYjmdrkn+Y1qQXBbMv2xYva9puXQTLZO5kWZzHGa0fw6CG6UcfDUDFB5EHK3VAuSqgLAEoVhkVRhtOChkFk84y4mjnVJmLieOJcQugL1iSsaC4ejUGsgysyYrUWIgV5Twl83fJJv5uMNYghhcAPrAbfkvB/+f/qHkvhW8Fo+ewomzwyt+SmD84OIR9WFWo7yGHH4XY3cUG3Le4CPsZGnmSsG5/o+ViFsWLMu6AJwKHF+gZD0GMYHgJRU1F88PGvElEB+S2j9VcHH9FzZzhc6FkIVN8u+/ajPLeGhaj9WWEsqCjQzUxNeFbWMsZaY="
  databaseSealedSecret: "AgAVZzjIvJjslBVZu6o47y+XpcsqyO/NOGIrn6vFeVTS8wca0O5lIPfTkArjEN7Ci10zoqAihAPQ7BURbF2abWif39kFkNZg3JsTzBQjb+Hc6F4yTnksIDhJwCs+uKOX7qzhMHYK5pcPgG7IXhLO3JI5oNL5pxmpWTNDe/4wmg4kLYpY/aJyym37NjZd4vLeK9XV7mmNp4Gz8XgHU5QdgwixuPNbWeP2yahptLCroftabBF54ha12jEgFwK7G9FJwZMhz7KyhkO6jNRBtkVooyps3ClG+fNoBTMnRtaSj+8KLG1cc3lowj+n/9WmRzU8JJDy8mPEndsh4oNlaUltMEgKFKhE/EkRGcwXhShstlZ3+POZw1L0nUB5kvVzFIW05GkzRXc5J9Jw9yc7ta815yq3CnRePG8deEENxN1Qwoay5yOlXw7AJJjUd5buWu2c18qPwkA2lqmEnyloah4GrORTLl1dvIaloSSK8B+kGBzayOJPChAzPg+Fuz9xkMSLkCoxVzYsX0VkHl1uGbxPRjYLEQ50SyZmnMxmj98vjoOprm5xaKa2af72gdc93rRBqc4KEWlPE4cDd2SBZ92JgeR/c7jK0yRFp0ZU221Jzek/t/M7h0bfjwrYg3U1ebUbWBCe/7m37P8+q7mIqh0wEs0sMDLvLZqaR81lbdmc8f+O3pnPO4UbsHGO2Kby95QUfLBLRHGHmlGwuf+kEhu4GdaNBzvGlpCbUCNk"
  usernameSealedSecret: "AgCSARYX5kRyU5I7nPtFbtT/N8hed40W+OlUB6HCcZ4ol3iE/jeC7gW/wdwCn/OODaROVj0f5+sstSRN2r6YE2wtqSduxA8yyMDwaNV8TowwilVlXVQ3s+RGlEB7S0Qn8RwHLvk1hdkHzU+oAPydn13amUHBtNSOf1C6FQnd9zh1Ss0O0zKx0d7+0ydWNtibLR5lVJ/6/9SVyHDmBA8W0023GEVmD6oM2wn01jIXgk7p2nh4QYnlGEx044HFIljo9eW+u06vaprBQEdpFGif/Eby5KSiTc9sIj4s4T6MU10zTwcoJTxCYBi/6dmUYQtPmlmmFRBr+7JkeTmnV+yvscSNJeOQcM+QK4LiGXHpdfbD2nEshXFC+0wwGGfXhP7N4hg30Ik4Z4DqAl3AO+QYWYu6zGFiGWMK1SOmfzWx3ODbUlPLPjwp+AE4mg56A0lEk/xsVioQk8zLTQN+BXISUzT7LCUj9KfV2zL8MB0R1uCq28ZXH7JKr1JfQt4vrUZaA6SNwJnrnF+gvo5cZHs6gxYhxchl5ggCPrYPR16MwBuB15XcGFFOGw09fLorbLFpVncpdcEeLy0g84xmc9tamouiSnVFEGSkzdkiqY1X6AaqWCftBLIPNwz3vCpEqBY8YH2Eszo13vIPklezQfplSziIvqHHxAoVt9X/gb9eAwm9b/lKCKvTame377zzhOC6wHLHSzy5c1VGjDP9dvYrbVNL"
  passwordSealedSecret: "AgDL56Yb3VpkIum9fjiwZIjNI+JX0nKFDBT/ejYiLEVczbGdXaN+N1HBq0Bep6I0gC2UxTtBWjNAdSnMGy7mL5jRoImbRK7ST/AmsQIkCqxdijz30cbHAqH4xAq/F4HTJWsNR9RIZ12Rra99rV57AqAEZl34zf+AcVdXw1VzeAnkWY0gR8fj/QajTNxAELRcEai4b887D2O2OGBmqmeQsDt0WPOlJkZjwYIbQ5em0FpS7n89a4TeBL7OZ4+IS6vhjOkOOPLl28pokS2J1RvzgRyq+VK3jIDJDkhscbGy47cHp/y7IwxdOUOyc32e35JTwW1XLPJotPJIzojxHO/1pOsVV+QNA317wPCSz3qVTQ76i7dEH9z3ZmOXVISTv0IuDL/XZw5Hd+cuF5GsqowWm9a1ZlysDQr4/JTJLY49L7uXVYIrg1GG8AatJisJ6RquBJvGz5uh812oKe9XoW+WEaum+Mmlx4vAJ9HLbXmDTSevidXTylyi9WW6E2uo3dxe7p091z9N6Mq5y55Phwt+hT4ke0oWFlqpZkQ+dQyPatMJqPdZIow/Ooj9bGSxZX12BVVNVaamwWntcvh5kXh1/fLUy0D6nqZFZ94SpbtVS3lIBaOjhxRW0GAFaBbpFybYnq57hV2StT2SuGH7MZIvKT/jD1ABfcC85SZcc+H6yBBK8ztpLyYMjhUNhapzwb7mEt6Q/mlgAyukWEllGMdvYE7ML+ekWF3f808="
  portSealedSecret: "AgA0np2oakTr6dJMAdRlvjI8IaTe+UxyIYIb/SClVzSe5gHo3BBDufqC7Q83D4VlM58yA9LrvAlTr2Zmx5yXdEYHbmAoFmUV3xFri1HXIj0Xg0yX8GQGtM289EdY5/+8lwDvBa8R6DP50+gte91pwu5YU0wrb8jOl7y0QFB2Q2ZQWZXHOEpaZRY5Jpa6VUn2sN3FJpSEtc5NTzS2i/WCoTIm3ae7JPbQYGu2+cv4/bZFsnj35b5FJf6/X7dmBlSHPG4Idq2GHNk6KTKPX+pLmFYyngyJ9w6E2VZAmQqELgZppt0qCo0qMKMKQ8WZ+yUP8uwb5JYKzfTMQzPowcQovP3gf4FUwfdcr+ICxY+uV0SFluPXmgh3AdlPqZyNhsL7i3dnq54wqKrVdQiMUgcXR7LfZRqMaGIZb4Ff11fjHT2/usPkqW/qMrDopSAT581kx1apnvd7bTub6Iwv1MGz2CKH3VzSEmY2z1Z43ON3/RxY+YQy6l3sTmboHgwOtjbRB/xvHG+aUpO7MzESLsx1ziWY6VzAfYjYCz7tao7Nq1RZyUYqUof9ax5M+i4vHMhom4GQh+j85mWwdQ2DYmQjXUXMtoRQzczL4I8t8VT/e3bWHe5ZNJ8iOLyq32nIWH0nbqBm+wCEHfsheF8lp+j5+teBi8HGJXQp+fcyGC1EBrMB1DPuA6c/EcXtvuPrvmWECYAxhIXVcQ=="
customWebsiteSealedSecret: AgCMpUhHm3fmB6WWP7Uk10JklAn99h6w5GfssXJjJKiz+05BUl7F5X20OClVHzvhZ3XiaeiXDSRPshBtNQYt4wi54GHwxovMch95W5OOTFLTS4KmJpQMOxMveg29VTcSOyw8Z0kMHBKeQydNyq/hpru8uGGA43V79dI2mXzGw2GMpxoX2aicvdBuhJ0vN2tVoClOBKYwXdtHpjbMuTyUalnw0CJuHV6nlbLp8FKP/DZ65diZI16fyitjCeRw4pfn6OXubWLX5x9lH+7ZflT3iQuhvUBtI2mQZ+3RNkxTN6zN9htRbIZIVccxDKfYbbvoI5ssFGcQmSqzIqpiLVtTD5EoPsssLIHnCB+Me6Iv6Wqa78xd707XmlxSXIOBTNk+NIs+f9tcEsmqB99iMq2nSZz/H8alsmrCZ1/2yqLGWUQdGhuKs7pY0OoN3Th5Bry5z48eVlT1Ummg+pZUj2Aw+BqGPqhao9HE4W7A7JaOxMVtg76U2DluRQ/5bZlWWfZ+b5QtBNypBxL1deUBiHq1WQxYEcMBoqmdELxU2prLb35nsSZXANvJ2Wp++XF/MYfVfZmm8dVKqbr5tOwUhrojwYcjKX6gJs3L3H2NzfM+vf8nYk1dPLB0J1Zd+dgKoxh+Nn+FBc/uhJqwcTB6HdKg1ogOP/NkiF/DQAOCPnW0bBk3RgNyImjoBakgO9Y+bIKEdyfpKGaUPy0wrddjQXirltSkoVkUQ7h3K0xnJw6pISvKgW/jWxNRR7p3OaPoanJXl9ZrJMTBvQl9bNlGrMahT/7adw86FaTne/2dTsWmZxKU7ahgz8YC3jiwr0f7FAmcZ0SrfG/NQJwBjQHzPlYPQkF5VsZ4HNa3ENYKa5ebbrUy0LTrymUnrg==
organisms:
 ebolavirus-sudan:
    schema:
      image: "https://cdn.britannica.com/01/179201-050-FED1B381/filamentous-ebolavirus-particles-scanning-electron-micrograph-cell.jpg?w=400&h=300&c=crop"
      instanceName: "Ebolavirus Sudan"
      metadata:
        - name: date
          type: date
        - name: region
          type: string
          generateIndex: true
          autocomplete: true
        - name: country
          type: string
          generateIndex: true
          autocomplete: true
        - name: division
          type: string
          generateIndex: true
          autocomplete: true
        - name: host
          type: string
          autocomplete: true
        - name: pango_lineage
          type: pango_lineage
          autocomplete: true
          required: true
      website:
        tableColumns:
          - country
          - division
          - date
          - pango_lineage
        defaultOrder: descending
        defaultOrderBy: date
      silo:
        dateToSortBy: date
        partitionBy: pango_lineage
    preprocessing:
      image: ghcr.io/loculus-project/preprocessing-dummy
      args:
        - "--watch"
      warnings: true
      errors: true
      randomWarnError: true
    referenceGenomes:
      nucleotideSequences:
        - name: "main"
          sequence: "[[URL:https://cov2tree.nyc3.cdn.digitaloceanspaces.com/reference.txt]]"
      genes: []
 cchf:
    schema:
      image: "https://live.staticflickr.com/821/41541604722_ec7630e697_b.jpg"
      instanceName: "Crimean-Congo haemorrhagic fever virus"
      metadata:
        - name: date
          type: date
        - name: region
          type: string
          generateIndex: true
          autocomplete: true
        - name: country
          type: string
          generateIndex: true
          autocomplete: true
        - name: division
          type: string
          generateIndex: true
          autocomplete: true
        - name: host
          type: string
          autocomplete: true
        - name: pango_lineage
          type: pango_lineage
          autocomplete: true
          required: true
      website:
        tableColumns:
          - country
          - division
          - date
          - pango_lineage
        defaultOrder: descending
        defaultOrderBy: date
      silo:
        dateToSortBy: date
        partitionBy: pango_lineage
    preprocessing:
      image: ghcr.io/loculus-project/preprocessing-dummy
      args:
        - "--watch"
      warnings: true
      errors: true
      randomWarnError: true
    referenceGenomes:
      nucleotideSequences:
        - name: "main"
          sequence: "[[URL:https://cov2tree.nyc3.cdn.digitaloceanspaces.com/reference.txt]]"
      genes: []
 west-nile-virus:
    schema:
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/West_Nile_Virus_Image.jpg/1200px-West_Nile_Virus_Image.jpg"
      instanceName: "West Nile Virus"
      metadata:
        - name: date
          type: date
        - name: region
          type: string
          generateIndex: true
          autocomplete: true
        - name: country
          type: string
          generateIndex: true
          autocomplete: true
        - name: division
          type: string
          generateIndex: true
          autocomplete: true
        - name: host
          type: string
          autocomplete: true
        - name: pango_lineage
          type: pango_lineage
          autocomplete: true
          required: true
      website:
        tableColumns:
          - country
          - division
          - date
          - pango_lineage
        defaultOrder: descending
        defaultOrderBy: date
      silo:
        dateToSortBy: date
        partitionBy: pango_lineage
    preprocessing:
      image: ghcr.io/loculus-project/preprocessing-dummy
      args:
        - "--watch"
      warnings: true
      errors: true
      randomWarnError: true
    referenceGenomes:
      nucleotideSequences:
        - name: "main"
          sequence: "[[URL:https://cov2tree.nyc3.cdn.digitaloceanspaces.com/reference.txt]]"
      genes: []
 cchf:
    schema:
      image: "https://live.staticflickr.com/821/41541604722_ec7630e697_b.jpg"
      instanceName: "Crimean-Congo haemorrhagic fever virus"
      metadata:
        - name: date
          type: date
        - name: region
          type: string
          generateIndex: true
          autocomplete: true
        - name: country
          type: string
          generateIndex: true
          autocomplete: true
        - name: division
          type: string
          generateIndex: true
          autocomplete: true
        - name: host
          type: string
          autocomplete: true
        - name: pango_lineage
          type: pango_lineage
          autocomplete: true
          required: true
      website:
        tableColumns:
          - country
          - division
          - date
          - pango_lineage
        defaultOrder: descending
        defaultOrderBy: date
      silo:
        dateToSortBy: date
        partitionBy: pango_lineage
    preprocessing:
      image: ghcr.io/loculus-project/preprocessing-dummy
      args:
        - "--watch"
      warnings: true
      errors: true
      randomWarnError: true
    referenceGenomes:
      nucleotideSequences:
        - name: "main"
          sequence: "[[URL:https://cov2tree.nyc3.cdn.digitaloceanspaces.com/reference.txt]]"
      genes: []
 ebolavirus-zaire:
    schema:
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Ebola_Virus_-_Electron_Micrograph.tiff/lossy-page1-440px-Ebola_Virus_-_Electron_Micrograph.tiff.jpg"
      instanceName: "Ebolavirus Zaire"
      metadata:
        - name: date
          type: date
        - name: region
          type: string
          generateIndex: true
          autocomplete: true
        - name: country
          type: string
          generateIndex: true
          autocomplete: true
        - name: division
          type: string
          generateIndex: true
          autocomplete: true
        - name: host
          type: string
          autocomplete: true
        - name: pango_lineage
          type: pango_lineage
          autocomplete: true
          required: true
      website:
        tableColumns:
          - country
          - division
          - date
          - pango_lineage
        defaultOrder: descending
        defaultOrderBy: date
      silo:
        dateToSortBy: date
        partitionBy: pango_lineage
    preprocessing:
      image: ghcr.io/loculus-project/preprocessing-dummy
      args:
        - "--watch"
      warnings: true
      errors: true
      randomWarnError: true
    referenceGenomes:
      nucleotideSequences:
        - name: "main"
          sequence: "[[URL:https://cov2tree.nyc3.cdn.digitaloceanspaces.com/reference.txt]]"
      genes: []
